"""Initial

Revision ID: 29310aa6e332
Revises: 9148bcbed622
Create Date: 2022-06-17 19:28:31.897096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29310aa6e332'
down_revision = '9148bcbed622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('relation_id', sa.String(), nullable=False))
    op.create_unique_constraint('uix_1', 'relations', ['relation_id', 'children_id'])
    op.drop_column('relations', 'shop_unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('shop_unit_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_1', 'relations', type_='unique')
    op.drop_column('relations', 'relation_id')
    # ### end Alembic commands ###
