"""Initial

Revision ID: 589113b338b2
Revises: 29310aa6e332
Create Date: 2022-06-18 20:34:10.443408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589113b338b2'
down_revision = '29310aa6e332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('shop_unit_id', sa.String(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('shop_unit_id', 'update_date', name=op.f('pk__history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
