"""Initial

Revision ID: 61bd2cdad215
Revises: 830fa3eb6145
Create Date: 2022-06-20 20:20:01.253381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bd2cdad215'
down_revision = '830fa3eb6145'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_2', 'history', type_='unique')
    op.create_unique_constraint('uix_2', 'history', ['shop_unit_id', 'update_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_2', 'history', type_='unique')
    op.create_unique_constraint('uix_2', 'history', ['shop_unit_id', 'update_date', 'price'])
    # ### end Alembic commands ###
