"""Initial

Revision ID: 830fa3eb6145
Revises: bd4f4247dada
Create Date: 2022-06-20 15:59:43.040374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830fa3eb6145'
down_revision = 'bd4f4247dada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_2', 'history', ['shop_unit_id', 'update_date', 'price'])
    op.create_unique_constraint('uix_1', 'relations', ['relation_id', 'children_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'relations', type_='unique')
    op.drop_constraint('uix_2', 'history', type_='unique')
    # ### end Alembic commands ###
