"""Initial

Revision ID: 83dde7000228
Revises: 
Create Date: 2022-06-15 21:50:12.171819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dde7000228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('shop_unit_id', sa.String(), nullable=False),
    sa.Column('children_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shop_unit_id', 'children_id', name=op.f('pk__relations'))
    )
    op.create_table('shop_units',
    sa.Column('shop_unit_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('shop_unit_id', name=op.f('pk__shop_units'))
    )
    op.create_index(op.f('ix__shop_units__name'), 'shop_units', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__shop_units__name'), table_name='shop_units')
    op.drop_table('shop_units')
    op.drop_table('relations')
    # ### end Alembic commands ###
