"""Initial

Revision ID: 9148bcbed622
Revises: 83dde7000228
Create Date: 2022-06-15 22:01:14.085418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9148bcbed622'
down_revision = '83dde7000228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_units', 'parent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_units', 'parent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
