"""Initial

Revision ID: bd4f4247dada
Revises: 
Create Date: 2022-06-19 14:22:22.948849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4f4247dada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('shop_unit_id', sa.String(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False)
    )
    op.create_table('relations',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('children_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('relation_id', 'children_id', name=op.f('pk__relations')),
    sa.UniqueConstraint('relation_id', 'children_id', name='uix_1')
    )
    op.create_table('shop_units',
    sa.Column('shop_unit_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('shop_unit_id', name=op.f('pk__shop_units'))
    )
    op.create_index(op.f('ix__shop_units__name'), 'shop_units', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__shop_units__name'), table_name='shop_units')
    op.drop_table('shop_units')
    op.drop_table('relations')
    op.drop_table('history')
    # ### end Alembic commands ###
